### ISSUE TITLE
Export Model to Grafico Files Unexpected Behavior

### ISSUE THREAD

**Issue by VinceAxe** [archimatetool/archi-modelrepository-plugin#102]
Working on some diff feature, I needed to have the Model Changes exported to the Diff Folder 
--> Thus I call Export Model To Grafico Files function
But it appears that a commit is **mandatory** after a call to this function ... I did not, start switching branches of my model, and it started to get messy ...

I suspect that it is because of the Git Add command called inside the function ...

I tried to think a way around, but I can't use the Reset function, since it hard reset ...

I'm not sure how to deal with all of this, but I was not prepared about that behavior with the Grafico Export (perhaps it's normal, but it needs to be explicite tho)

**Comment by Phillipus** [comment]
It depends what you are trying to do.

`IArchiRepository#exportModelToGraficoFiles()` will serialise the model to the xml files. If the model has chnaged since the last time this was called, then git will report that changes have been made and a commit or an abort is required. This method does Stage the files (Add Command) to remove files that only have line endings different.

So, effectively this method saves XML files and does an Add command.
