### ISSUE TITLE
[Feature Request] Switch Branch without commit

### ISSUE THREAD

**Issue by VinceAxe** [archimatetool/archi-modelrepository-plugin#115]
As of today it seems impossible to switch branch without making a commit.

It seems reasonably normal to not be able to switch branch if the repos isn't clean (git standard behavior) however, when you are absolutely sure you didn't do anything to the repos (and Archi force you to make an empty commit, because of version or something) I would like to see something like "abort any changes and switch"

I know there is a command in Collaboration Menu that allow you to "Abort Uncommitted Changes" ... still it asks me to commit even after using it.

Regards,

**Comment by jbsarrodie** [comment]
>As of today it seems impossible to switch branch without making a commit.

Not really. At the end of the day a branch is a pointer onto a commit id, so a branch really exists only if there's a commit. But if you have no changes in your model you can still switch branch. If you're been asked to commit this is because there are some changes.

>I know there is a command in Collaboration Menu that allow you to "Abort Uncommitted Changes" ... still it asks me to commit even after using it.

Again, if you're been asked to commit, this is because there are some changes. Are you sure you've not simply opened a model which were saved with a different version of Archi (and thus, each time you open it you change the internal model version, which you have to commit) ?

**Comment by VinceAxe** [comment]
> Again, if you're been asked to commit, this is because there are some changes. Are you sure you've not simply opened a model which were saved with a different version of Archi (and thus, each time you open it you change the internal model version, which you have to commit) ?

That is precisely the problem I have, I was aware of it :( 
But since I am navigating in old branches, or let my coworkers work as comfy as they want, I don't want to make any commit on these, hence the possibility of this feature request

**Comment by Phillipus** [comment]
I'll close this, as this is being addressed now.
