### ISSUE TITLE
Error while trying to sync with GIT repo : Packagefile corruption

### ISSUE THREAD

**Issue by jonaritz** [archimatetool/archi-modelrepository-plugin#161]
Logs cant be attached due to View Error button is disabled

### Version of Archi
4.6.0
201911111111

### Operating System
Windows

### Expected Behaviour
Fetch the GIT repo

### Actual Behaviour
A meanless error is given:
![image](https://user-images.githubusercontent.com/1209983/107512475-305c5500-6ba7-11eb-9e81-e4c1aa66b7dd.png)

**Comment by Phillipus** [comment]
Moved this to the coArchi issue tracker.

Sorry, there's not enough info to diagnose this, and it's unlikely that it's anything that can be fixed in coArchi itself. Perhaps the local git files are corrupted? 

https://www.google.co.uk/search?ei=sdcjYKe5EeWEhbIP7sacsAQ&q=packfile+corruption+detected+invalid+distance+too+far+back&oq=packfile+corruption+detected+inv&gs_lcp=CgZwc3ktYWIQAxgAMgYIABAWEB4yBggAEBYQHjoHCAAQRxCwA1DLDViNFGCKIWgBcAJ4AIABhgGIAeIDkgEDNC4xmAEAoAEBqgEHZ3dzLXdpesgBCLgBAsABAQ&sclient=psy-ab

Might be worth deleting the local copy and re-importing from the online repo. Are you using latest coArchi?

**Comment by jonaritz** [comment]
Hey!

thanks for replying so quickly!

I might have a local problem as you suggest. Gonna investigate the local
git files cuzz the problem might be there.

thanks a lot for the hint!
Aritz
