### ISSUE TITLE
problem to import a remote model with archi collaborative

### ISSUE THREAD

**Issue by nadinew** [archimatetool/archi-modelrepository-plugin#170]
when i try to import a remote model ( brancn master ) i have a message et when i say ok the remote model doesn't open in the workspace
![Sans titre 1](https://user-images.githubusercontent.com/1303578/122246840-2f299480-cec7-11eb-8ba2-b3858a3e77d1.jpg)

**Comment by jbsarrodie** [comment]
Hi Nadine,

This is related to an underlying corruption of the model which can happen in some edge cases. The root cause is most certainly a relationship that was created and later updated to change its start or end (could be cause by a manual operation or the merge of some elements). In some cases, the underlying relationship has changed but a connexion in a view hasn't.

Since version 4.7, Archi has been enhanced to look for such inconsistencies and now refuses to open such model.

To fix it you have to run a script on the model using Archi 4.6.

The whole process is described [here](https://forum.archimatetool.com/index.php?topic=959.msg5226#msg5226).

JB

**Comment by nadinew** [comment]
I install archi 4.6 and the plug in collaborative and import the remote model
but how can i run this script with archi 4.6 I don't find the plug in jarchi for archi4.6

**Comment by Phillipus** [comment]
> Since version 4.7, Archi has been enhanced to look for such inconsistencies and now refuses to open such model.

@jbsarrodie Are you sure? The ModelChecker only checks when saving a model.

**Comment by jbsarrodie** [comment]
> @jbsarrodie Are you sure? The ModelChecker only checks when saving a model.

Yes, during import, coArchi has to create the temp.archimate file from the repository and thus has to save it. That's why this issue is raised.

**Comment by jbsarrodie** [comment]
> I install archi 4.6 and the plug in collaborative and import the remote model
> but how can i run this script with archi 4.6 I don't find the plug in jarchi for archi4.6

If you installed Archi 4.6 using the custom package I created for the team last year, jArchi is already included. If you can't find it I can send it to you by email, just let me know.

**Comment by Phillipus** [comment]
> 
> 
> > @jbsarrodie Are you sure? The ModelChecker only checks when saving a model.
> 
> Yes, during import, coArchi has to create the temp.archimate file from the repository and thus has to save it. That's why this issue is raised.

Ah, yes. Could one open the `temp.archimate` file directly bypassing coArchi?

**Comment by jbsarrodie** [comment]
> Ah, yes. Could one open the `temp.archimate` file directly bypassing coArchi?

`temp.Archimate` file only exist when the import process worked fine, so the only way to get it locally is to downgrade.

Another option is to find someone who already imported the model and to let it run the script and then commit/publish changes.

**Comment by nadinew** [comment]
can you send me jarchi for 4.6
thanks
