### ISSUE TITLE
Cannot merge: " file is not directory or folder.xml does not exist"

### ISSUE THREAD

**Issue by mgrueso** [archimatetool/archi-modelrepository-plugin#173]
### Version of Archi, Operating System

Archi 4.8.1
Windows 10  
### Version of this plug-in

ARchi collaboration 0.7.1.202101
### Any other plug-ins installed?

Archi scripting (jarchi)  1.1.0 
Lightbox  for archi  1.0.1 
### Expected Behaviour

I need your help with a log;   because when i try to do a merge and there exist any error the only message that the application get me "is  file is not directory or folder.xml does not exist " , i was search  about this error  and i want that the system give me a log with archimate  internal id for the folder that produce the error, and the full archimate path  and i thinking that i cant resolve the problem   
### Actual Behaviour

the message is only merge error and the message 
### Steps to Reproduce the Behaviour
1.this is error that is reported in different issue 
2.https://forum.archimatetool.com/index.php?topic=988.0
3.

**Comment by Phillipus** [comment]
(I've edited the issue title to better summarise the problem)

As for logging coArchi errors in coArchi 1, this is minimal (but there will be more in coArchi 2) so that won't help in this case.

As you say, the error has been seen before - https://forum.archimatetool.com/index.php?topic=988.0 - is there any advice in that thread that can help?

**Comment by mgrueso** [comment]
thanks you
