### ISSUE TITLE
Single source of truth multiple tools.

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [archimatetool/archi-modelrepository-plugin#194]
I like your initiative for this plugin. With this plugin I can use Github or alike as a single source of truth for  a community architecture. Bravo. Now I have a related question from a concurrent point of view. You see, my organization uses a specific Archimate tool, not Archi, as the  single source of truth for our architects.  Not very successful. It's a black hole. Nothing comes out and cocreation is a distant thought.

So I'm theorizing about connecting our specific tool to a public modelrepository like Github.  This  tool does not know Grafico, however it knows AMEFF. They hold the same information but they are organized and serialized differently.  Do you know about any work done on transforming a grafico -structure on Github into a Ameff-file so it can be cloned, modified with out Archimate tool en  then pushed back?  Just to get things rolling.

**Comment by jbsarrodie** [comment]
Hi, that's more a question for the [forum](https://forum.archimatetool.com/index.php), but as Archi is able to load an AMEFF file, then one can do pretty muuch everything manually (load the AMEFF file and publish it to git). Ideally, one could use Archi to automate the the process, but the missing part asof today is that [Archi CLI](https://github.com/archimatetool/archi/wiki/Archi-Command-Line-Interface) doesn't not support commit and publish.

**Comment by GeraldGrootRoessink** [comment]
@jbsarrodie: thanks. I have seen it many times:  a modelling tool positioned as a central repository. Using git is so much better. Just trying to show this with a demo. I  was thinking maybe there is some XSLT  between Grafico and AMEFF. But at this time we can do it manually. In the end, I am sure, everybody is using Archi.

**Comment by jbsarrodie** [comment]
> I was thinking maybe there is some XSLT between Grafico and AMEFF

That's not possible because Grafico involves not only its own XML schema (in fact, Eclipse EMF schema), but also a folder hierarchy which mimics the internal structure of the model, bith being subject to changes.

>Just trying to show this with a demo.

That's of course not a free solution, but maybe look at [ArchiRepo](https://archirepo.com/): that's a good example of leveraging AMEFF to share and act on an ArchiMate model, whatever the tool used to "author" it. That's not based on git nor decentralized though.

**Comment by GeraldGrootRoessink** [comment]
The main folder structure of Archi is fixed, is it not?

**Comment by jbsarrodie** [comment]
> The main folder structure of Archi is fixed, is it not?

Yes, but the folder hierarchy of Grafico is also based on your own, user-defined, folders. So in order to convert one single AMEFF file, you'd have to generate multiple small XML files based on the internal model organisation structure inside AMEFF, knowing that it is not necessarily compatible with Archi constraints: in Archi a element can only be stored under the folder hierarchy related to its type, while in an AMEFF file, folder can store any kind of concept or view.
