### ISSUE TITLE
Add support for Workspace with multiple models.

### ISSUE THREAD

**Issue by ebbypeter** [archimatetool/archi-modelrepository-plugin#51]
I have multiple solutions / projects for a single client. Currently I have to create multiple repositories (each with one model) to mange my diagrams.
It would be wonderful to support multiple models per repository (Each repository in this case can be considered as a workspace). In this case, I will need only one repository per client.

**Comment by Phillipus** [comment]
There was a discussion on this in issue #49

**Comment by ebbypeter** [comment]
Looking into the way the model is implemented, the whole model is contained in the "model" folder with folder.xml in the model folder that defines the name and identifier of the model. 
What need in that regard is to support multiple model folders to allow for workspace type usage, (each folder will be a separate model). 
The Archi collaboration UI paradigm will be compatible with this with an additional option to show the models available in a particular workspace.

**Comment by jbsarrodie** [comment]
Multiple "model folders" inside the same git repository is not possible because change history is for the repository, not per folder.

Anyway, the collaboration plugin is designed arround the logic that one model equals one repository.

The real question is: why do you want to have only one repository? What's the issue for you in creating multiple repositories? At the end all those models/repositories will be visible and managed through the collaboration workspace.

**Comment by Phillipus** [comment]
I guess the granularity of one model per repository is the same as one code project per repository. If you have more than one per model, the change history can get complicated.

**Comment by jbsarrodie** [comment]
@ebbypeter I'm closing this issue as, per design, we'll not have multiple models per repository.
