### ISSUE TITLE
Add support for signing

### ISSUE THREAD

**Issue by danielwagn3r** [archimatetool/archi-modelrepository-plugin#58]
Add support for signing of commits and tags, it would be great if the configuration is shared with the local Git installation - usually developers have setup everything there already.

**Comment by jbsarrodie** [comment]
TBH, this is not on our (informal) roadmap but we can keep an eye on it.

>it would be great if the configuration is shared with the local Git installation - usually developers have setup everything there already.

Archi doesn't really targets developpers, and the fact that we uses git under the hood is just because that's a great piece of software, but we don't want to make it "visible" to the end user. Thus there is little chances that we would integrate with already existing git setup on a workstation.
